apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: {{ .Values.pod.numberOfNginxReplicas }} 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.pod.initContainerImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
      {{- with .Values.pod.ocirSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      ${ is_arm_node_shape ? "nodeSelector:" : "" }
        ${ is_arm_node_shape ? "kubernetes.io/arch: arm64" : "" }